# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    #node.js
    - nodejs_version: 0.10
    - nodejs_version: 0.11
    - nodejs_version: 0.12
    #io.js
    - nodejs_version: 2.5.0

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm -g install npm@2.12.1
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g gulp
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - ps: gulp test
  - cmd: gulp test
